### ISSUE TITLE
null

### ISSUE THREAD

**Issue by UtsavDonda07** [afzalali15/shopx#11]
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: type 'Null' is not a subtype of type 'String'

**Comment by sat4talk** [comment]
you will encounter many errors like this..
check the type of variable and according to type change ternary true value as either " " or 0.0 e.g
for double and String type.. change it as below
rating: json["rating"] == null ? **0.0** : json["rating"].toDouble(),
category: json["category"] == null ? **""** : json["category"],

There are many errors still.. I have resolved all errors. interested tell me
