### ISSUE TITLE
How to ontap on the product? 

### ISSUE THREAD

**Issue by JackyGohSG** [afzalali15/shopx#3]
How do I do a ontap gesture on the selected index / product tile?

**Comment by afzalali15** [comment]
You can wrap Card widget inside ProductTile with InkWell. It will give you OnTap gesture.. InkWell generally goes with Material Widget so you can have something like this..

Material
|__ InkWell
.....|__Card

**Comment by PeterTF656** [comment]
@afzalali15 Dear Afzal, Thank you for making this tutorial! I have one question regarding ontap on each product on the grid with getx: So when you tap on a single product, you should be navigated to a specific product page, and when loading that single product page, the detailed information of that product is read from the database. So how can I first keep tracking of which product I clicked (the product id) and then send that to a "read" operation? It seems two different controllers are needed; One for storing the product id clicked, and the other for storing the content of the product clicked...
